name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install modules
      run: |
        sudo apt-get install -y  libimlib2-dev
        make install

    - name: Build module
      run: make build

    - name: Run tests
      run: make test
